name: Create and Publish

on:
  workflow_dispatch: 

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io/lbrassard/recruitment-test-devops
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          ref: init

      - name: Log in to the Container registry 
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09
        with:
          context: ./Question 3/
          push: true
          tags: ${{ env.REGISTRY }}/mssql:2019-latest
          labels: Nectari